export const GET_CURRENT_LOCATION_REQUEST = 'GET_CURRENT_LOCATION_REQUEST';
export const GET_CURRENT_LOCATION_SUCCESS = 'GET_CURRENT_LOCATION_SUCCESS';
export const GET_CURRENT_LOCATION_FAILURE = 'GET_CURRENT_LOCATION_FAILURE';

export const ADD_WAYPOINT_INPUT = 'ADD_WAYPOINT_INPUT';
export const DELETE_WAYPOINT_INPUT = 'DELETE_WAYPOINT_INPUT';

export const SET_ORIGIN_POINT = 'SET_ORIGIN_POINT';
export const SET_WAYPOINT = 'SET_WAYPOINT';
export const SET_DESTINATION_POINT = 'SET_DESTINATION_POINT';

export const CLEAR_WAYPOINTS = 'CLEAR_WAYPOINTS';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';
export const CLEAR_MAIN_POINTS = 'CLEAR_MAIN_POINTS';

export const GET_ROUTE_REQUEST = 'GET_ROUTE_REQUEST';
export const GET_ROUTE_SUCCESS = 'GET_ROUTE_SUCCESS';
export const GET_ROUTE_FAILURE = 'GET_ROUTE_FAILURE';

export const GET_DISTANCE_REQUEST = 'GET_DISTANCE_REQUEST';
export const GET_DISTANCE_SUCCESS = 'GET_DISTANCE_SUCCESS';
export const GET_DISTANCE_FAILURE = 'GET_DISTANCE_FAILURE';

export const SET_API_KEY_REQUEST = 'SET_API_KEY_REQUEST';
export const SET_API_KEY_SUCCESS = 'SET_API_KEY_SUCCESS';
export const SET_API_KEY_FAILURE = 'SET_API_KEY_FAILURE';

export const GET_API_KEY_REQUEST = 'GET_API_KEY_REQUEST';
export const GET_API_KEY_SUCCESS = 'GET_API_KEY_SUCCESS';
export const GET_API_KEY_FAILURE = 'GET_API_KEY_FAILURE';

export const SELECTED_MODE = 'SELECTED_MODE';