export const SET_WAYPOINT = 'SET_WAYPOINT';
export const GET_DISTANCE = 'GET_DISTANCE';
export const FIND_MIN_DISTATION = 'FIND_MIN_DISTATION';

export const GET_CURRENT_LOCATION_REQUEST = 'GET_CURRENT_LOCATION_REQUEST';
export const GET_CURRENT_LOCATION_SUCCESS = 'GET_CURRENT_LOCATION_SUCCESS';
export const GET_CURRENT_LOCATION_FAILURE = 'GET_CURRENT_LOCATION_FAILURE';

export const SET_ORIGIN_POINT = 'SET_ORIGIN_POINT';
export const SET_DESTINATION_POINT = 'SET_DESTINATION_POINT';
export const CLEAR_WAYPOINTS = 'CLEAR_WAYPOINTS';
export const CLEAR_MAIN_POINTS = 'CLEAR_MAIN_POINTS';

export const GET_ROUTE_REQUEST = 'GET_ROUTE_REQUEST';
export const GET_ROUTE_SUCCESS = 'GET_ROUTE_SUCCESS';
export const GET_ROUTE_FAILURE = 'GET_ROUTE_FAILURE';

export const GET_DISTANCE_REQUEST = 'GET_DISTANCE_REQUEST';
export const GET_DISTANCE_SUCCESS = 'GET_DISTANCE_SUCCESS';
export const GET_DISTANCE_FAILURE = 'GET_DISTANCE_FAILURE';
