export const SET_WAYPOINT = 'SET_WAYPOINT';
export const GET_ROUTE_SUCCESS = 'GET_ROUTE_SUCCESS';
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const SET_ORIGIN_POINT = 'SET_ORIGIN_POINT';
export const SET_DESTINATION_POINT = 'SET_DESTINATION_POINT';